/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisStatsRouteImport } from './routes/vis-stats'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentFormatRouteImport } from './routes/tournament-format'
import { Route as StatLoginRouteImport } from './routes/stat-login'
import { Route as StatAdminRouteImport } from './routes/stat-admin'
import { Route as SocialRouteImport } from './routes/social'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as PlayerDexRouteImport } from './routes/player-dex'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRegistrationsRouteImport } from './routes/admin-registrations'
import { Route as AdminDbConsoleRouteImport } from './routes/admin-db-console'
import { Route as AdminDbCheckRouteImport } from './routes/admin-db-check'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveTournamentIdRouteImport } from './routes/live.$tournamentId'
import { Route as ApiPlayersRouteImport } from './routes/api.players'
import { Route as ApiMessagesRouteImport } from './routes/api.messages'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAdminResetRouteImport } from './routes/api.admin-reset'
import { Route as ApiTournamentIdRouteImport } from './routes/api.tournament.$id'
import { Route as ApiImageIdRouteImport } from './routes/api.image.$id'

const VisStatsRoute = VisStatsRouteImport.update({
  id: '/vis-stats',
  path: '/vis-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentFormatRoute = TournamentFormatRouteImport.update({
  id: '/tournament-format',
  path: '/tournament-format',
  getParentRoute: () => rootRouteImport,
} as any)
const StatLoginRoute = StatLoginRouteImport.update({
  id: '/stat-login',
  path: '/stat-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatAdminRoute = StatAdminRouteImport.update({
  id: '/stat-admin',
  path: '/stat-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerDexRoute = PlayerDexRouteImport.update({
  id: '/player-dex',
  path: '/player-dex',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin-registrations',
  path: '/admin-registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDbConsoleRoute = AdminDbConsoleRouteImport.update({
  id: '/admin-db-console',
  path: '/admin-db-console',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDbCheckRoute = AdminDbCheckRouteImport.update({
  id: '/admin-db-check',
  path: '/admin-db-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTournamentIdRoute = LiveTournamentIdRouteImport.update({
  id: '/live/$tournamentId',
  path: '/live/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayersRoute = ApiPlayersRouteImport.update({
  id: '/api/players',
  path: '/api/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetRoute = ApiAdminResetRouteImport.update({
  id: '/api/admin-reset',
  path: '/api/admin-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentIdRoute = ApiTournamentIdRouteImport.update({
  id: '/api/tournament/$id',
  path: '/api/tournament/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageIdRoute = ApiImageIdRouteImport.update({
  id: '/api/image/$id',
  path: '/api/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-db-check': typeof AdminDbCheckRoute
  '/admin-db-console': typeof AdminDbConsoleRoute
  '/admin-registrations': typeof AdminRegistrationsRoute
  '/assessment': typeof AssessmentRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRoute
  '/configuration': typeof ConfigurationRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/player-dex': typeof PlayerDexRoute
  '/polls': typeof PollsRoute
  '/registration': typeof RegistrationRoute
  '/social': typeof SocialRoute
  '/stat-admin': typeof StatAdminRoute
  '/stat-login': typeof StatLoginRoute
  '/tournament-format': typeof TournamentFormatRoute
  '/tournaments': typeof TournamentsRoute
  '/vis-stats': typeof VisStatsRoute
  '/api/admin-reset': typeof ApiAdminResetRoute
  '/api/chat': typeof ApiChatRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/players': typeof ApiPlayersRoute
  '/live/$tournamentId': typeof LiveTournamentIdRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/api/tournament/$id': typeof ApiTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-db-check': typeof AdminDbCheckRoute
  '/admin-db-console': typeof AdminDbConsoleRoute
  '/admin-registrations': typeof AdminRegistrationsRoute
  '/assessment': typeof AssessmentRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRoute
  '/configuration': typeof ConfigurationRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/player-dex': typeof PlayerDexRoute
  '/polls': typeof PollsRoute
  '/registration': typeof RegistrationRoute
  '/social': typeof SocialRoute
  '/stat-admin': typeof StatAdminRoute
  '/stat-login': typeof StatLoginRoute
  '/tournament-format': typeof TournamentFormatRoute
  '/tournaments': typeof TournamentsRoute
  '/vis-stats': typeof VisStatsRoute
  '/api/admin-reset': typeof ApiAdminResetRoute
  '/api/chat': typeof ApiChatRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/players': typeof ApiPlayersRoute
  '/live/$tournamentId': typeof LiveTournamentIdRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/api/tournament/$id': typeof ApiTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-db-check': typeof AdminDbCheckRoute
  '/admin-db-console': typeof AdminDbConsoleRoute
  '/admin-registrations': typeof AdminRegistrationsRoute
  '/assessment': typeof AssessmentRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRoute
  '/configuration': typeof ConfigurationRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/player-dex': typeof PlayerDexRoute
  '/polls': typeof PollsRoute
  '/registration': typeof RegistrationRoute
  '/social': typeof SocialRoute
  '/stat-admin': typeof StatAdminRoute
  '/stat-login': typeof StatLoginRoute
  '/tournament-format': typeof TournamentFormatRoute
  '/tournaments': typeof TournamentsRoute
  '/vis-stats': typeof VisStatsRoute
  '/api/admin-reset': typeof ApiAdminResetRoute
  '/api/chat': typeof ApiChatRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/players': typeof ApiPlayersRoute
  '/live/$tournamentId': typeof LiveTournamentIdRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/api/tournament/$id': typeof ApiTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/admin-db-check'
    | '/admin-db-console'
    | '/admin-registrations'
    | '/assessment'
    | '/chat'
    | '/communities'
    | '/configuration'
    | '/gallery'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/me'
    | '/player-dex'
    | '/polls'
    | '/registration'
    | '/social'
    | '/stat-admin'
    | '/stat-login'
    | '/tournament-format'
    | '/tournaments'
    | '/vis-stats'
    | '/api/admin-reset'
    | '/api/chat'
    | '/api/messages'
    | '/api/players'
    | '/live/$tournamentId'
    | '/api/image/$id'
    | '/api/tournament/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/admin-db-check'
    | '/admin-db-console'
    | '/admin-registrations'
    | '/assessment'
    | '/chat'
    | '/communities'
    | '/configuration'
    | '/gallery'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/me'
    | '/player-dex'
    | '/polls'
    | '/registration'
    | '/social'
    | '/stat-admin'
    | '/stat-login'
    | '/tournament-format'
    | '/tournaments'
    | '/vis-stats'
    | '/api/admin-reset'
    | '/api/chat'
    | '/api/messages'
    | '/api/players'
    | '/live/$tournamentId'
    | '/api/image/$id'
    | '/api/tournament/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/admin-db-check'
    | '/admin-db-console'
    | '/admin-registrations'
    | '/assessment'
    | '/chat'
    | '/communities'
    | '/configuration'
    | '/gallery'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/me'
    | '/player-dex'
    | '/polls'
    | '/registration'
    | '/social'
    | '/stat-admin'
    | '/stat-login'
    | '/tournament-format'
    | '/tournaments'
    | '/vis-stats'
    | '/api/admin-reset'
    | '/api/chat'
    | '/api/messages'
    | '/api/players'
    | '/live/$tournamentId'
    | '/api/image/$id'
    | '/api/tournament/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDbCheckRoute: typeof AdminDbCheckRoute
  AdminDbConsoleRoute: typeof AdminDbConsoleRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AssessmentRoute: typeof AssessmentRoute
  ChatRoute: typeof ChatRoute
  CommunitiesRoute: typeof CommunitiesRoute
  ConfigurationRoute: typeof ConfigurationRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PlayerDexRoute: typeof PlayerDexRoute
  PollsRoute: typeof PollsRoute
  RegistrationRoute: typeof RegistrationRoute
  SocialRoute: typeof SocialRoute
  StatAdminRoute: typeof StatAdminRoute
  StatLoginRoute: typeof StatLoginRoute
  TournamentFormatRoute: typeof TournamentFormatRoute
  TournamentsRoute: typeof TournamentsRoute
  VisStatsRoute: typeof VisStatsRoute
  ApiAdminResetRoute: typeof ApiAdminResetRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiPlayersRoute: typeof ApiPlayersRoute
  LiveTournamentIdRoute: typeof LiveTournamentIdRoute
  ApiImageIdRoute: typeof ApiImageIdRoute
  ApiTournamentIdRoute: typeof ApiTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vis-stats': {
      id: '/vis-stats'
      path: '/vis-stats'
      fullPath: '/vis-stats'
      preLoaderRoute: typeof VisStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament-format': {
      id: '/tournament-format'
      path: '/tournament-format'
      fullPath: '/tournament-format'
      preLoaderRoute: typeof TournamentFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stat-login': {
      id: '/stat-login'
      path: '/stat-login'
      fullPath: '/stat-login'
      preLoaderRoute: typeof StatLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stat-admin': {
      id: '/stat-admin'
      path: '/stat-admin'
      fullPath: '/stat-admin'
      preLoaderRoute: typeof StatAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-dex': {
      id: '/player-dex'
      path: '/player-dex'
      fullPath: '/player-dex'
      preLoaderRoute: typeof PlayerDexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-registrations': {
      id: '/admin-registrations'
      path: '/admin-registrations'
      fullPath: '/admin-registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-db-console': {
      id: '/admin-db-console'
      path: '/admin-db-console'
      fullPath: '/admin-db-console'
      preLoaderRoute: typeof AdminDbConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-db-check': {
      id: '/admin-db-check'
      path: '/admin-db-check'
      fullPath: '/admin-db-check'
      preLoaderRoute: typeof AdminDbCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$tournamentId': {
      id: '/live/$tournamentId'
      path: '/live/$tournamentId'
      fullPath: '/live/$tournamentId'
      preLoaderRoute: typeof LiveTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/players': {
      id: '/api/players'
      path: '/api/players'
      fullPath: '/api/players'
      preLoaderRoute: typeof ApiPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-reset': {
      id: '/api/admin-reset'
      path: '/api/admin-reset'
      fullPath: '/api/admin-reset'
      preLoaderRoute: typeof ApiAdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/$id': {
      id: '/api/tournament/$id'
      path: '/api/tournament/$id'
      fullPath: '/api/tournament/$id'
      preLoaderRoute: typeof ApiTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$id': {
      id: '/api/image/$id'
      path: '/api/image/$id'
      fullPath: '/api/image/$id'
      preLoaderRoute: typeof ApiImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDbCheckRoute: AdminDbCheckRoute,
  AdminDbConsoleRoute: AdminDbConsoleRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AssessmentRoute: AssessmentRoute,
  ChatRoute: ChatRoute,
  CommunitiesRoute: CommunitiesRoute,
  ConfigurationRoute: ConfigurationRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PlayerDexRoute: PlayerDexRoute,
  PollsRoute: PollsRoute,
  RegistrationRoute: RegistrationRoute,
  SocialRoute: SocialRoute,
  StatAdminRoute: StatAdminRoute,
  StatLoginRoute: StatLoginRoute,
  TournamentFormatRoute: TournamentFormatRoute,
  TournamentsRoute: TournamentsRoute,
  VisStatsRoute: VisStatsRoute,
  ApiAdminResetRoute: ApiAdminResetRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiPlayersRoute: ApiPlayersRoute,
  LiveTournamentIdRoute: LiveTournamentIdRoute,
  ApiImageIdRoute: ApiImageIdRoute,
  ApiTournamentIdRoute: ApiTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
